version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/badges-checkout"
      - "/slack-notify"
      - "/badges-jacoco"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
