name: 'slack notify'
description: 'send message to slack channel'
inputs:
  channel:
    description: 'slack channel'
    required: false
    default: 'eresept'
  username:
    description: 'slack usernamme'
    required: false
    default: 'eresept ${{ github.event.repository.name }}'
  icon:
    description: 'slack icon emoji'
    required: false
    default: ':slack:'
  title-success:
    description: 'slack success title'
    required: false
    default: ' '
  title-failure:
    description: 'slack failure title'
    required: false
    default: ' '
  title-cancelled:
    description: 'slack cancelled title'
    required: false
    default: ' '
  message-success:
    description: 'slack success message'
    required: false
    default: ' '
  message-failure:
    description: 'slack failure message'
    required: false
    default: "See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} for details"
  message-cancelled:
    description: 'slack cancelled message'
    required: false
    default: ' '
  footer:
    description: 'slack footer'
    required: false
    default: 'eresept © 2022-2026'
  minimal:
    description: 'If set to true, removes: Ref, Event,  Actions URL and Commit from the message. You can optionally whitelist any of these 4 removed values by passing it comma separated to the variable instead of true'
    required: false
    default: ''
  webhook:
    description: 'slack webhook'
    required: true
  status:
    description: failure, success or cancelled
    required: false
    default: 'success'

runs:
  using: composite
  steps:
    - run: echo "minimal=$( if ([ ${EVENT} != 'push' ] && [ ${EVENT} != 'pull_request' ]) || [ ${MIN} = 'true' ]; then echo true; else echo ${MIN}; fi)"  >> $GITHUB_ENV
      shell: bash
      env:
        EVENT: ${{ github.event_name }}
        MIN: ${{ inputs.minimal }}

    - if: ${{ inputs.status == 'success' && github.event_name != 'schedule' }}
      env:
        SLACK_CHANNEL: ${{ inputs.channel }}
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_USERNAME: "${{ inputs.username  }}"
        SLACK_TITLE: "${{ inputs.title-success }}"
        SLACK_COLOR: "good"
        SLACK_ICON_EMOJI: "${{ inputs.icon }}"
        SLACK_FOOTER: "${{ inputs.footer }}"
        SLACK_MESSAGE: "${{ inputs.message-success }}"
        MSG_MINIMAL: ${{ env.minimal }}
      uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
    - if: ${{ inputs.status == 'failure' }}
      env:
        SLACK_CHANNEL: ${{ inputs.channel }}
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_USERNAME: "${{ inputs.username  }}"
        SLACK_TITLE: "${{ inputs.title-failure }}"
        SLACK_COLOR: "danger"
        SLACK_ICON_EMOJI: "${{ inputs.icon }}"
        SLACK_FOOTER: "${{ inputs.footer }}"
        SLACK_MESSAGE: "${{ inputs.message-failure }}"
        MSG_MINIMAL: ${{ env.minimal }}
      uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
    - if: ${{ inputs.status == 'cancelled' }}
      env:
        SLACK_CHANNEL: ${{ inputs.channel }}
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_USERNAME: "${{ inputs.username  }}"
        SLACK_TITLE: "${{ inputs.title-cancelled }}"
        SLACK_COLOR: "warning"
        SLACK_ICON_EMOJI: "${{ inputs.icon }}"
        SLACK_FOOTER: "${{ inputs.footer }}"
        SLACK_MESSAGE: "${{ inputs.message-cancelled }}"
        MSG_MINIMAL: ${{ env.minimal }}
      uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
