name: 'dispatch action'
description: 'dispatches an action'
inputs:
  owner:
    description: 'the repository owner'
    required: false
    default: 'navikt'
  repo:
    description: 'the repository'
    required: true
  action:
    description: 'the filename of the action to run'
    required: true
  ref:
    description: 'the reference of the workflow run. The reference can be a branch, tag, or a commit SHA'
    required: false
    default: 'main'
  inputs:
    description: 'inputs to pass to the workflow, must be a JSON string'
    required: false
    default: '{}'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        $GITHUB_ACTION_PATH/dispatch.sh "${{ inputs.owner }}" "${{ inputs.repo }}" "${{ inputs.action }}" "${{ secrets.GITHUB_TOKEN }}" "${{ inputs.ref }}" "${{ inputs.inputs }}"
