name: 'dispatch action'
description: 'dispatches an action'
inputs:
  owner:
    description: 'the repository owner'
    required: false
    default: 'navikt'
  repo:
    description: 'the repository'
    required: true
  action:
    description: 'the filename of the action to run'
    required: true
  ref:
    description: 'the reference of the workflow run. The reference can be a branch, tag, or a commit SHA'
    required: false
    default: 'main'
  token:
    description: 'the Github access token with access to the repository.'
    required: true
  inputs:
    description: 'inputs to pass to the workflow, must be a JSON string'
    required: false
    default: '{}'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -X POST "https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$ACTION/dispatches" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" -H "Authorization: Bearer ${{ inputs.token }}" --data "{\"ref\":\"${{ inputs.ref }}\",\"inputs\": ${{ inputs.input }} }"
#        $GITHUB_ACTION_PATH/dispatch.sh "${{ inputs.owner }}" "${{ inputs.repo }}" "${{ inputs.action }}" "${{ inputs.token }}" "${{ inputs.ref }}" "${{ inputs.inputs }}"
