# In this workflow, we use a dedicated branch for storing the badges.
# It assumes that the badges branch already exists. That branch can otherwise
# be empty, as its only purpose is to store the coverage badges. Why? Well, if
# our main branch has required checks or reviews, the default GITHUB_TOKEN won't
# be able to push to it. By storing the badges in a dedicated branch, this is not
# an issue (just don't put any required checks or required reviews on the badges
# branch). Note that since we won't be storing anything else in the badges branch,
# we just put them in the root of that branch.
#
# IMPORTANT: Take note of the 2 checkout steps that are necessary for this variation.
# The first is the usual checkout step. The second checks out the dedicated badges branch
# (see the ref input) nested inside the other in the path badges (see the path input).
# So locally within the rest of this workflow run, we'll have access to the badges branch
# within a badges directory.
#
# It does nothing if the badges branch doesn't exist.

name: 'create coverage badge and publish jacoco reports'
description: 'creates a coverage badge to stick on README files, saves it in a badges branch and uploads the jacoco coverage report as workflow artifact'
inputs:
  jacoco-dir:
    description: 'location of the jacoco coverage reports and csv file'
    required: false
    default: 'target/site/jacoco'
  jacoco-name:
    description: 'the name of the csv file'
    required: false
    default: 'jacoco.csv'
runs:
  using: "composite"
  steps:
    - if: ${{ env.BADGES == 'true' && github.event_name != 'pull_request' }}
      shell: bash
      run: $GITHUB_ACTION_PATH/mkbadges.sh ${{ inputs.jacoco-dir }}/${{ inputs.jacoco-name }} $GITHUB_ACTION_PATH ${{ runner.temp }}
    - if: ${{ env.BADGES == 'true' && github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 #v4.3.5
      with:
        name: jacoco-report
        path: ${{ inputs.jacoco-dir }}
