# In this workflow, we use a dedicated branch for storing the badges.
# It assumes that the badges branch already exists. That branch can otherwise
# be empty, as its only purpose is to store the coverage badges. Why? Well, if
# our main branch has required checks or reviews, the default GITHUB_TOKEN won't
# be able to push to it. By storing the badges in a dedicated branch, this is not
# an issue (just don't put any required checks or required reviews on the badges
# branch). Note that since we won't be storing anything else in the badges branch,
# we just put them in the root of that branch.
#
# IMPORTANT: Take note of the 2 checkout steps that are necessary for this variation.
# The first is the usual checkout step. The second checks out the dedicated badges branch
# (see the ref input) nested inside of the other in the path badges (see the path input).
# So locally within the rest of this workflow run, we'll have access to the badges branch
# within a badges directory.
#
# It does nothing if the badges branch doesn't exist.

name: 'create coverage badge and publish jacoco reports'
description: 'creates a coverage badge to stick on README files, saves it a badges branch and uploads the jacoco coverage report as workflow artifact'
inputs:
  jacoco-dir:
    description: 'where is the jacoco coverage reports and csv file'
    required: false
    default: 'target/site/jacoco'
runs:
  using: "composite"
  steps:
    - id: check-for-branch
      run: |
        git show-ref --verify --quiet 'ref/heads/badges'
        echo "::set-output name=branch-exists::$(if [ $? == 0 ]; then echo true; else echo false; fi)"
      shell: bash
    - if: ${{ steps.check-for-branch.outputs.branch-exists == 'true' }}
      uses: actions/checkout@v2 # checks out the branch that stores the coverage badges
      with:
        ref: badges
        path: badges
    - if: ${{ steps.check-for-branch.outputs.branch-exists == 'true' }}
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true
        generate-coverage-badge: true
        #fail-if-branches-less-than: 0.10
        #fail-if-coverage-less-than: 0.70
        jacoco-csv-file: ${{ inputs.jacoco.dir }}/jacoco.csv
    - if: ${{ steps.check-for-branch.outputs.branch-exists == 'true' }}
      run: |
        cd badges
        if [[ `git status --porcelain *.svg` ]]; then
          git config user.name "GitHub Actions Bot (${{ github.actor }})"
          git config user.email "actions@github.com"
          git add *.svg
          git commit -m "Autogenerated JaCoCo coverage badges" *.svg
          git push
        fi
      shell: bash
    - if: ${{ steps.check-for-branch.outputs.branch-exists == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: ${{ inputs.jacoco.dir }}
