potential-bugs:
  DoubleMutabilityForCollection:
    excludes: ['**/test/**']
  MapGetWithNotNullAssertionOperator:
    excludes: ['**/test/**']
  UnsafeCallOnNullableType:
    active: false

style:
  VarCouldBeVal:
    excludes: ['**/test/**']