name: 'delete packages'
description: 'deletes packages from github'

inputs:
  owner:
    description: owner of the package (user or organization)
    required: true
    default: 'navikt'

  name:
    description: name of the package containing the version to delete.
    required: true

  token:
    description: token with the necessary scopes to delete package versions.
    required: true

  tag:
    description: tag to delete
    required: false

  dry-run:
    description: if true will only report what would have been done, but not delete anything
    required: false
    default: 'false'

  type:
    description: type of package, container or maven
    required: false
    default: 'container'

  untagged-keep-latest:
    description: delete all untagged images except the last N
    required: false

  untagged-older-than:
    description: delete all untagged images older than N in days.
    required: false

  tag-regex:
    description: regex to apply to tags. images will be included if ANY of the tags match the entered regex. If this is set, tagged-keep-latest must also be set
    required: false

  tagged-keep-latest:
    description: delete all tagged images matching tag-regex except the last N. if this is set, tag-regex must also be set
    required: false

runs:
  using: 'node12'
  main: 'index.js'