name: generate an attestation for the image, re-usable
on:
  workflow_call:
    inputs:
      application:
        description: 'the application to attest'
        required: true
        type: string
      image:
        description: 'the docker image'
        required: true
        type: string
        # no default
      digest:
        description: 'the digest of the image'
        required: false
        type: string
        # no default

env:
  TZ: Europe/Oslo

jobs:
  attest:
    timeout-minutes: 10
    name: Generate attestation of ${{ inputs.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Docker login
        uses: nais/login@c88ada9ce583928e1c84d2fd5c45cfacdd18d5de #v0
        id: login
        with:
          team: teameresept

      - name: Generate SBOM, attest and sign image
        id: attest-sign
        uses: nais/attest-sign@518e541b5bd2eaff9ed7cb7fd305ec940b66fdaa #v2.0.5
        with:
          image_ref: ${{ steps.login.outputs.registry }}/${{ inputs.application }}@${{ inputs.digest }}
