name: generate an attestation for the image, re-usable
on:
  workflow_call:
    inputs:
      application:
        description: 'the application to attest'
        required: true
        type: string
      image:
        description: 'the docker image'
        required: true
        type: string
        # no default
      digest:
        description: 'the digest of the image'
        required: false
        type: string
        # no default

env:
  TZ: Europe/Oslo

jobs:
  attest:
    timeout-minutes: 10
    name: Generate attestation of ${{ inputs.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Docker login
        uses: nais/login@d6ab5d83f735e9f155eb9d7d29cd20ae46820ea9 #v0
        id: login
        with:
          team: teameresept

      - name: Generate SBOM, attest and sign image
        id: attest-sign
        uses: nais/attest-sign@d8ec1989b5d1eb59809b050149713002f3de8e2d #v2.0.6
        with:
          image_ref: ${{ steps.login.outputs.registry }}/${{ inputs.application }}@${{ inputs.digest }}
