name: generate an attestation for the image, re-usable
on:
  workflow_call:
    inputs:
      application:
        description: 'the application to attest'
        required: true
        type: string
      image:
        description: 'the docker image'
        required: true
        type: string
        # no default
      digest:
        description: 'the digest of the image'
        required: false
        type: string
        # no default

env:
  TZ: Europe/Oslo

jobs:
  attest:
    timeout-minutes: 10
    name: Generate attestation of ${{ inputs.image }}
    runs-on: ubuntu-latest
    permissions:
      actions: read # for private repositories
      contents: read
      id-token: write
    steps:
      - name: Docker login
        uses: nais/login@e7cf2c159677dc7c7d599feff5f808f2bf59c7cf #v0
        id: login
        with:
          team: teameresept

      - name: Generate SBOM, attest and sign image
        id: attest-sign
        uses: nais/attest-sign@v1
        with:
          image_ref: ${{ steps.login.outputs.registry }}/${{ inputs.application }}@${{ inputs.digest }}
