name: Gradle build, re-usable
on:
  workflow_call:
    secrets:
      webhook:
        description: 'slack webhook'
        required: false
      token:
        description: 'github token'
        required: true

jobs:
  build:
    name: Build ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.repository.name }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      slack_webhook: ${{ secrets.webhook }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 #v3.11.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Set some variables
        run: |
          echo "starttime=$(date +%s)" >> $GITHUB_ENV
          sudo timedatectl set-timezone "Europe/Oslo"
          echo "lastcommit=$(git log -1 --date=format:'%Y-%m-%d %T' --format=%cd)" >> $GITHUB_ENV

      - name: Get commit message
        run: |
          echo "commit_msg=$(git log -1 --oneline)" >> $GITHUB_ENV
          echo "commit_sha=$(git log -1 --format=%H)" >> $GITHUB_ENV

      - name: Compile and test
        run: ./gradlew build jacocoTestReport --no-daemon

      - name: Checkout badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-checkout@main

      - name: Create coverage badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-jacoco@main
        with:
          jacoco-dir: build/reports/jacoco/test
          jacoco-name: jacocoTestReport.csv

      - name: Last commit badge
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'last commit'
          right: '${{ env.lastcommit }}'
          color: 'blue'
          filename: 'last-commit'
          logo: 'calendar'

      - name: Calculate execution time
        run: |
          END_TIME=$(date +%s)
          echo "exectime=$(( $END_TIME - ${{ env.starttime }} ))" >> $GITHUB_ENV

      - name: Time used badge
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'build execution time'
          right: '${{ env.exectime }}'
          color: 'blue'
          filename: 'build-exec-time'
          logo: 'stopwatch'

      - name: Commit badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-commit@main

      - name: Summary
        run: echo "### Built **${{ github.event.repository.name }}** in ${{ env.exectime }} seconds" >> $GITHUB_STEP_SUMMARY

      - name: report to slack
        if: always()
        uses: navikt/eresept-actions/slack-notify@main
        with:
          username: "build ${{ github.event.repository.name }}"
          icon: ":github:"
          title-success: "Built _*${{ github.event.repository.name }}*_ in ${{ env.exectime }} seconds"
          title-failure: "Build failure in _*${{ github.event.repository.name }}*_"
          title-cancelled: "Build of _*${{ github.event.repository.name }}*_ was cancelled"
          message-success: "${{ env.commit_msg }}"
          message-cancelled: "${{ env.commit_msg }}"
          webhook: ${{ secrets.webhook }}
