name: Gradle build, re-usable
on:
  workflow_call:
    inputs:
      java-version:
        description: the java version to use
        required: false
        type: number
        default: 21
      coverage-task:
        description: 'name of coverage task'
        required: false
        default: 'jacocoTestReport'
        type: string
      coverage-report-dir:
        description: 'path to coverage report'
        required: false
        default: 'build/reports/jacoco/test'
        type: string
    secrets:
      webhook:
        description: 'slack webhook'
        required: false
      token:
        description: 'github token'
        required: true

jobs:
  build:
    timeout-minutes: 30
    name: Build ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.repository.name }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      actions: read
      issues: read
      checks: write
      contents: write
      pull-requests: write
      security-events: write
    env:
      slack_webhook: ${{ secrets.webhook }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 #v4.3.0
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'

      - name: Set some variables
        run: |
          echo "starttime=$(date +%s)" >> $GITHUB_ENV
          sudo timedatectl set-timezone "Europe/Oslo"
          echo "lastcommit=$(git log -1 --date=format:'%Y-%m-%d %T' --format=%cd)" >> $GITHUB_ENV

      - name: Get commit message
        run: |
          echo "commit_msg=$(git log -1 --oneline)" >> $GITHUB_ENV
          echo "commit_sha=$(git log -1 --format=%H)" >> $GITHUB_ENV

      - name: Initialze CodeQL Analysis
        uses: github/codeql-action/init@294a9d92911152fe08befb9ec03e240add280cb3 # v3.26.8
        with:
          languages: java

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 #v4
        with:
          dependency-graph: generate-and-submit

      - name: Build with gradle
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: ./gradlew ${{ inputs.coverage-task }} --no-daemon

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@294a9d92911152fe08befb9ec03e240add280cb3 # v3.26.8
        with:
          category: "/language:java"

      - name: Publish results (unit test)
        uses: EnricoMi/publish-unit-test-result-action@82082dac68ad6a19d980f8ce817e108b9f496c2a #v2.17.1
        if: success() || failure()
        with:
          files: "**/build/test-results/test/TEST-*.xml"

      - name: Checkout badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-checkout@main

      - name: Create coverage badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-jacoco@main
        with:
          jacoco-dir: ${{ inputs.coverage-report-dir }}
          jacoco-name: ${{ inputs.coverage-task }}.csv

      - name: Last commit badge
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'last commit'
          right: '${{ env.lastcommit }}'
          color: 'blue'
          filename: 'last-commit'
          logo: 'calendar'

      - name: Calculate execution time
        run: |
          END_TIME=$(date +%s)
          echo "exectime=$(( $END_TIME - ${{ env.starttime }} ))" >> $GITHUB_ENV

      - name: Time used badge
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'build execution time'
          right: '${{ env.exectime }}'
          color: 'blue'
          filename: 'build-exec-time'
          logo: 'stopwatch'

      - name: Commit badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-commit@main

      - name: Summary
        run: echo "### Built **${{ github.event.repository.name }}** in ${{ env.exectime }} seconds" >> $GITHUB_STEP_SUMMARY

      - name: report to slack
        if: always()
        uses: navikt/eresept-actions/slack-notify@main
        with:
          status: "${{ job.status }}"
          username: "build ${{ github.event.repository.name }}"
          icon: ":github2:"
          title-success: "Built _*${{ github.event.repository.name }}*_ in ${{ env.exectime }} seconds"
          title-failure: "Build failure in _*${{ github.event.repository.name }}*_"
          title-cancelled: "Build of _*${{ github.event.repository.name }}*_ was cancelled"
          message-success: "${{ env.commit_msg }}"
          message-cancelled: "${{ env.commit_msg }}"
          webhook: ${{ secrets.webhook }}
