name: Gradle build, re-usable
on:
  workflow_call:
    inputs:
      channel:
        description: 'slack channel'
        required: false
        type: string
        default: 'eresept'
      footer:
        description: 'slack footer'
        required: false
        type: string
        default: 'eresept © 2023'
    secrets:
      webhook:
        description: 'slack webhook'
        required: false
      token:
        description: 'github token'
        required: true

jobs:
  build:
    name: Build ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.repository.name }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      slack_webhook: ${{ secrets.webhook }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 #v3.11.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Set some variables
        run: |
          echo "starttime=$(date +%s)" >> $GITHUB_ENV
          sudo timedatectl set-timezone "Europe/Oslo"
          echo "lastcommit=$(git log -1 --date=format:'%Y-%m-%d %T' --format=%cd)" >> $GITHUB_ENV

      - name: Get commit message
        run: |
          echo "commit_msg=$(git log -1 --oneline)" >> $GITHUB_ENV
          echo "commit_sha=$(git log -1 --format=%H)" >> $GITHUB_ENV

      - name: Compile and test
        run: ./gradlew build jacocoTestReport --no-daemon

      - name: Checkout badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-checkout@main

      - name: Create coverage badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-jacoco@main
        with:
          jacoco-dir: build/reports/jacoco/test
          jacoco-name: jacocoTestReport.csv

      - name: Last commit badge
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'last commit'
          right: '${{ env.lastcommit }}'
          color: 'blue'
          filename: 'last-commit'
          logo: 'calendar'

      - name: Calculate execution time
        run: |
          END_TIME=$(date +%s)
          echo "exectime=$(( $END_TIME - ${{ env.starttime }} ))" >> $GITHUB_ENV

      - name: Time used badge
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'build execution time'
          right: '${{ env.exectime }}'
          color: 'blue'
          filename: 'build-exec-time'
          logo: 'stopwatch'

      - name: Commit badges
        if: ${{ github.event_name != 'pull_request' }}
        uses: navikt/eresept-actions/badges-commit@main

      - name: Summary
        run: echo "### Built **${{ github.event.repository.name }}** in ${{ env.exectime }} seconds" >> $GITHUB_STEP_SUMMARY

      - name: Report success?
        if: ${{ success() && env.slack_webhook != '' }}
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "build ${{ github.event.repository.name }}"
          SLACK_TITLE: "Built _*${{ github.event.repository.name }}*_ in ${{ env.exectime }} seconds"
          SLACK_COLOR: "good"
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_FOOTER: "${{ inputs.footer }}"
          SLACK_MESSAGE: "${{ env.commit_msg }}"
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 # v2
      - name: Report failure?
        if: ${{ failure() && env.slack_webhook != '' }}
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "build ${{ github.event.repository.name }}"
          SLACK_TITLE: "Build failure in _*${{ github.event.repository.name }}*_"
          SLACK_COLOR: "danger"
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_FOOTER: "${{ inputs.footer }}"
          SLACK_MESSAGE: "See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} for details"
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 # v2
      - name: Report cancellation?
        if: ${{ cancelled() && env.slack_webhook != '' }}
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "build ${{ github.event.repository.name }}"
          SLACK_TITLE: "Build of _*${{ github.event.repository.name }}*_ was cancelled"
          SLACK_COLOR: "warning"
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_FOOTER: "${{ inputs.footer }}"
          SLACK_MESSAGE: "${{ env.commit_msg }}"
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 # v2
