name: cleanup docker images, re-usable

on:
  workflow_call:
    secrets:
      token:
        description: 'github token'
        required: true

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "eresept-parent", "name": "github", "url": "https://maven.pkg.github.com/navikt/eresept-parent", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "eresept-parent", "username": "${{ github.actor }}", "password": "${{ secrets.token }}" }]'
          output_file: snyk-settings.xml
      - name: creates a project in your Snyk account to be continuously monitored
        uses: actions/github-script@v6
        with:
          script:
            const utils = require("../src/utils");
                        
            async function deleteTagRegexMatchOrderGreaterThan(config, octokit) {
              core.info(`🔎 finding latest tagged ${config.taggedKeepLatest} packages matching regex ${config.tagRegex}. Also finding latest untagged ${config.untaggedKeepLatest} packages...`);
            
              const pkgs = await utils.findPackageVersionsTagRegexMatchOrderGreaterThan(
                octokit,
                config.owner,
                config.name,
                config.type,
                config.taggedKeepLatest,
                config.untaggedKeepLatest,
                new RegExp(config.tagRegex));
            
              core.startGroup(`🗑 delete ${pkgs.length} packages`);
              
              for (const pkg of pkgs) {
                if (!config.dryRun) {
                  await utils.deletePackageVersion(
                  octokit,
                  config.owner,
                  config.name,
                  config.type,
                  pkg.id);
              }
              core.info(`✅ package #${pkg.id} deleted.`);
            }

            core.endGroup();
          }

          module.exports = { deleteTagRegexMatchOrderGreaterThan };


