name: Deploy applications, re-usable
on:
  workflow_call:
    inputs:
      applications:
        description: 'The applications to deploy (stringified JSON object listing application, eg: "[\"foo\",\"bar\"]")'
        required: true
        type: string
        # no default
      application-version:
        description: 'The version to deploy'
        required: false
        type: string
        # no default
      environments:
        description: 'The environments to deploy applications to (stringified JSON object listing application, eg: "[\"q1\",\"p\"]")'
        required: true
        type: string
        # no default
    secrets:
      token:
        description: 'Secret token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: ${{ fromJson(inputs.applications) }}
        environment: ${{ fromJson(inputs.environments) }}
    name: Deploy ${{ matrix.application }} ${{ inputs.application-version }} to ${{ matrix.environment }}
    steps:
      - shell: bash
        run: |
          curl -X POST \
          https://api.github.com/repos/navikt/${{ matrix.application }}/actions/workflows/03_deploy.yaml/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.token }}
          -d '{"ref":"main", "inputs": {"application-version":"${{ inputs.application-version }}", "environment":"${{ matrix.environment }}" }'
#      - uses: navikt/eresept-actions/dispatch@main
#        with:
#          repo: '${{ matrix.application }}'
#          action: '03_deploy.yaml'
#          token:  '${{ secrets.token }}'
#          inputs: '{"application-version": "${{ inputs.application-version }}", "environment": "${{ matrix.environment }}" }'
