name: Deploy applications, re-usable
on:
  workflow_call:
    inputs:
      channel:
        description: 'Slack channel'
        required: false
        type: string
        default: 'eresept'
      footer:
        description: 'Slack footer'
        required: false
        type: string
        default: 'eresept © 2022'
      applications:
        description: 'The applications to deploy (stringified JSON object listing application, eg: "[\"foo\",\"bar\"]")'
        required: true
        type: string
        # no default
      application-version:
        description: 'The version to deploy'
        required: false
        type: string
        # no default
      environments:
        description: 'The environments to deploy applications to (stringified JSON object listing application, eg: "[\"q1\",\"p\"]")'
        required: true
        type: string
        # no default
    secrets:
      webhook:
        description: 'Slack webhook'
        required: true
      deploy-key:
        description: 'NAIS deploy apikey'
        required: true
      token:
        description: 'token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: ${{ fromJson(inputs.applications) }}
        environment: ${{ fromJson(inputs.environments) }}
    name: Deploy ${{ matrix.application }} ${{ inputs.application-version }} to ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: navikt/${{ matrix.application }}
          token: ${{ secrets.token }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get start time
        id: starttime
        run: echo "::set-output name=starttime::$(date +%s)"

      - name: Set timezone
        run: sudo timedatectl set-timezone "Europe/Oslo"

      - name: Get version numbers and cluster
        id: vals
        run: |
          LASTVERSION=$(git tag --sort=-version:refname|head -1|tr -d 'v')
          INPUT_VERSION=${{ inputs.application-version }}
          RELVERSION=$(echo ${INPUT_VERSION:-$LASTVERSION}|sed 's/-.*//')
          echo "::set-output name=relversion::$RELVERSION"
          echo "::set-output name=cluster::$(if [ "${{ matrix.environment }}" == "p" ]; then echo prod-fss; else echo dev-fss ; fi)"
          POTSFIX=$(if [ '${{ matrix.environment }}' != 'p' -a '${{ matrix.environment }}' != 'q1' ]; then echo '-${{ matrix.environment }}'; fi)
          echo "::set-output name=deployapp::${{ matrix.application }}$POSTFIX"
          echo "::set-output name=deployappver::${{ matrix.application }}$POSTFIX:$RELVERSION"

      - name: Deploy ${{ steps.vals.outputs.deployapp }} to ${{matrix.environment }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.deploy-key }}
          CLUSTER: ${{ steps.vals.outputs.cluster }}
          RESOURCE: .nais/nais.yaml
          VARS: .nais/nais.vars.${{ matrix.environment }}.yaml
          IMAGE: ghcr.io/navikt/${{ matrix.application }}/${{ matrix.application }}:${{ steps.vals.outputs.relversion }}

      - name: Calculate execution time
        id: exectime
        run: |
          END_TIME=$(date +%s)
          echo "::set-output name=exectime::$(( $END_TIME - ${{ steps.starttime.outputs.starttime }} ))"

      - name: Report success?
        if: success()
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "deploy ${{ steps.vals.outputs.deployappver }} -> ${{ matrix.environment }}"
          SLACK_TITLE: "Deployed _*${{ steps.vals.outputs.deployappver }}*_ to _*${{ matrix.environment }}*_ in _*${{ steps.vals.outputs.cluster }}*_ in ${{ steps.exectime.outputs.exectime }} seconds"
          SLACK_MESSAGE: "${{ steps.vals.outputs.deployappver }}"
          SLACK_COLOR: "good"
          SLACK_ICON_EMOJI: ":nais:"
          MSG_MINIMAL: true
          SLACK_FOOTER: "${{ inputs.footer }}"
        uses: rtCamp/action-slack-notify@v2
      - name: Report failure?
        if: failure()
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "deploy ${{ steps.vals.outputs.deployappver }} -> ${{ matrix.environment }}"
          SLACK_TITLE: "Deploy of _*${{ steps.vals.outputs.deployappver }}*_ to _*${{ matrix.environment }}*_ in _*${{ steps.vals.outputs.cluster }}*_ failed"
          SLACK_MESSAGE: "${{ steps.vals.outputs.deployappver }}"
          SLACK_COLOR: "danger"
          SLACK_ICON_EMOJI: ":nais:"
          MSG_MINIMAL: true
          SLACK_FOOTER: "${{ inputs.footer }}"
        uses: rtCamp/action-slack-notify@v2
      - name: Report cancellation?
        if: cancelled()
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "deploy ${{ steps.vals.outputs.deployappver }} -> ${{ matrix.environment }}"
          SLACK_TITLE: "Deploy of _*${{ steps.vals.outputs.deployappver }}*_ to _*${{ steps.vals.outputs.cluster }}*_ in _*${{ steps.vals.outputs.cluster }}*_ was cancelled"
          SLACK_MESSAGE: "${{ steps.vals.outputs.deployappver }}"
          SLACK_COLOR: "warning"
          SLACK_ICON_EMOJI: ":nais:"
          MSG_MINIMAL: true
          SLACK_FOOTER: "${{ inputs.footer }}"
        uses: rtCamp/action-slack-notify@v2
