name: Deploy applications, re-usable
on:
  workflow_call:
    inputs:
      applications:
        description: 'The applications to deploy (stringified JSON object listing application, eg: "[\"foo\",\"bar\"]")'
        required: true
        type: string
        # no default
      application-version:
        description: 'The version to deploy'
        required: false
        type: string
        # no default
      environments:
        description: 'The environments to deploy applications to (stringified JSON object listing application, eg: "[\"q1\",\"p\"]")'
        required: true
        type: string
        # no default
    secrets:
      webhook:
        description: 'Slack webhook'
        required: true
      deploy-key:
        description: 'NAIS deploy apikey'
        required: true
      token:
        description: 'token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: ${{ fromJson(inputs.applications) }}
        environment: ${{ fromJson(inputs.environments) }}
    name: Deploy ${{ matrix.application }} ${{ inputs.application-version }} to ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        with:
          fetch-depth: 0
          repository: navikt/${{ matrix.application }}
          token: ${{ secrets.token }}

      - name: Start time and timezone
        run: |
          echo "starttime=$(date +%s)" >> $GITHUB_ENV
          sudo timedatectl set-timezone "Europe/Oslo"

      - name: Get version numbers and cluster
        run: |
          LASTVERSION=$(git tag --sort=-version:refname|head -1|tr -d 'v')
          INPUT_VERSION=${{ inputs.application-version }}
          RELVERSION=$(echo ${INPUT_VERSION:-$LASTVERSION}|sed 's/-.*//')
          echo "relversion=$RELVERSION" >> $GITHUB_ENV
          echo "cluster=$(if [ "${{ matrix.environment }}" == "p" ]; then echo prod-fss; else echo dev-fss ; fi)" >> $GITHUB_ENV
          POSTFIX=$(if [ '${{ matrix.environment }}' != 'p' -a '${{ matrix.environment }}' != 'q1' ]; then echo '-${{ matrix.environment }}'; else echo ''; fi)
          echo "deployapp=${{ matrix.application }}$POSTFIX" >> $GITHUB_ENV
          echo "deployappver=${{ matrix.application }}$POSTFIX:$RELVERSION" >> $GITHUB_ENV
          echo "deploydate=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Deploy ${{ env.deployapp }} to ${{matrix.environment }}
        uses: nais/deploy/actions/deploy@52ca39b063b55a406d9049e28431de2e3a6ac535 #v1
        env:
          APIKEY: ${{ secrets.deploy-key }}
          CLUSTER: ${{ env.cluster }}
          RESOURCE: .nais/nais.yaml
          VARS: .nais/nais.vars.${{ matrix.environment }}.yaml
          IMAGE: ghcr.io/navikt/${{ matrix.application }}/${{ matrix.application }}:${{ env.relversion }}

      - name: Calculate execution time
        run: |
          END_TIME=$(date +%s)
          echo "exectime=$(( $END_TIME - ${{ env.starttime }} ))" >> $GITHUB_ENV

      - name: Checkout badges
        uses: navikt/eresept-actions/badges-checkout@main

      - name: Deploy version badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: '${{ matrix.environment }} version'
          right: '${{ env.relversion }}'
          color: 'blue'
          filename: 'deploy-version-${{ matrix.environment }}'
          logo: 'tag'

      - name: Deploy date badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: '${{ matrix.environment }} date'
          right: '${{ env.deploydate }}'
          color: 'blue'
          filename: 'deploy-date-${{ matrix.environment }}'
          logo: 'calendar'

      - name: Commit badges
        uses: navikt/eresept-actions/badges-commit@main

      - name: Summary
        run: echo "### Deployed **${{ env.deployappver }}** to **${{ matrix.environment }}** in **${{ env.cluster }}** in ${{ env.exectime }} seconds" >> $GITHUB_STEP_SUMMARY

      - name: report to slack
        if: always()
        uses: navikt/eresept-actions/slack-notify@main
        with:
          status: "${{ job.status }}"
          username: "deploy ${{ env.deployappver }} -> ${{ matrix.environment }}"
          icon: ":naiser:"
          title-success: "Deployed _*${{ env.deployappver }}*_ to _*${{ matrix.environment }}*_ in _*${{ env.cluster }}*_ in ${{ env.exectime }} seconds"
          title-failure: "Deploy of _*${{ env.deployappver }}*_ to _*${{ matrix.environment }}*_ in _*${{ env.cluster }}*_ failed"
          title-cancelled: "Deploy of _*${{ env.deployappver }}*_ to _*${{ env.cluster }}*_ in _*${{ env.cluster }}*_ was cancelled"
          message-success: "${{ env.deployappver }}"
          message-cancelled: "${{ env.deployappver }}"
          webhook: ${{ secrets.webhook }}
