name: Deploy resource, re-usable
on:
  workflow_call:
    inputs:
      version:
        description: 'The version/tag to deploy, main or a tag'
        required: true
        type: string
      file:
        description: 'The resource file to deploy, without .yaml extension'
        required: true
        type: string
      vars:
        description: 'The file containing the template variables, without .yaml extension and cluster suffix'
        required: true
        type: string
      icon:
        description: 'The icon to use in slack message'
        required: true
        type: string
      cluster:
        description: 'The cluster to deploy the resource to'
        required: true
        type: string
        default: dev-fss
    secrets:
      webhook:
        description: 'Slack webhook'
        required: true

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      actions: read # for private repositories
      contents: write
      id-token: write
    name: deploy ${{ inputs.file }} to ${{ inputs.cluster }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0
          repository: ${{ github.event.repository.full_name}}
          ref: '${{ github.ref_name }}'
          persist-credentials: true
          show-progress: false

      - name: Create variables
        shell: bash
        run: |
          lasttag=$(git describe --tags --abbrev=0)
          tag=$(if [ "${VER}" == "main" ]; then echo $lasttag; else echo ${VER} | sed 's/ //g; s/v//'; fi)
          echo "deployver=$tag" >> $GITHUB_ENV
        env:
          VER: ${{ inputs.version }}

      - name: Templating
        id: template
        uses: navikt/eresept-actions/templating@main
        with:
          template: .nais/${{ inputs.file }}.yaml
          variables: .nais/${{ inputs.vars }}.${{ inputs.cluster }}.yaml

      - uses: nais/setup@ea33c90b68228e6f04fb34b88bfd8ab6ad523ce8 # v1.0.2
        with:
          team: teameresept

      - name: Deploy
        run: |
          nais apply ${RESOURCE} --environment ${CLUSTER} --wait
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ steps.template.outputs.output }}

      - name: Checkout badges
        uses: navikt/eresept-actions/badges-checkout@main

      - name: Deployed version badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: '${{ inputs.cluster }} version'
          right: '${{ env.deployver }}'
          color: 'blue'
          filename: '${{ inputs.cluster }}-${{ inputs.file }}-version'
          logo: 'tag'

      - name: Deployed date badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: '${{ inputs.cluster }} date'
          right: '${{ env.deploydate }}'
          color: 'blue'
          filename: '${{ inputs.cluster }}-${{ inputs.file }}-date'
          logo: 'calendar'

      - name: Commit badges
        uses: navikt/eresept-actions/badges-commit@main

      - name: report to slack
        if: always()
        uses: navikt/eresept-actions/slack-notify@main
        with:
          status: "${{ job.status }}"
          username: "eresept deploy ${{ inputs.file }}"
          icon: "${{ inputs.icon }}"
          title-success: "Deployed ${{ inputs.file }}:${{ env.deployver }} to ${{ inputs.cluster }}"
          title-failure: "Deploy of ${{ inputs.file }}:${{ env.deployver }} to ${{ inputs.cluster }} failed"
          title-cancelled: "Deploy of ${{ inputs.file }}:${{ env.deployver }} to ${{ inputs.cluster }} was cancelled"
          webhook: ${{ secrets.webhook }}
