name: Gradle release application, re-usable
on:
  workflow_call:
    inputs:
      java-version:
        description: the java version to use
        required: false
        type: number
        default: 21
      application:
        description: 'The application to release'
        required: true
        type: string
        # no default
      application-version:
        description: 'The version to release'
        required: false
        type: string
        # no default
      skip-tests:
        description: 'if execution of tests should be skipped'
        required: false
        type: boolean
        default: false
      sbom-build:
        description: 'command to use when building sbom'
        required: false
        type: string
        default: 'cyclonedxBom'
      sbom-path:
        description: 'where to find the sbom file'
        required: false
        type: string
        default: 'build/reports/bom.json'
    secrets:
      webhook:
        required: true
      token:
        required: true
      identity-provider:
        required: true

jobs:
  release:
    timeout-minutes: 40
    name: Release ${{ inputs.application }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        with:
          fetch-depth: 0
          repository: navikt/${{ inputs.application }}
          ref: '${{ github.ref_name }}'

      - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 #v4.3.0
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'

      - name: Set some variables
        run: |
          echo "starttime=$(date +%s)" >> $GITHUB_ENV
          sudo timedatectl set-timezone "Europe/Oslo"
          echo "buildarg=$(if [ '${{ inputs.skip-tests }}' = 'true' ]; then echo 'assemble'; else echo 'build'; fi)" >> $GITHUB_ENV 

      - name: get versions, changelog and more
        id: get-versions
        uses: navikt/eresept-actions/get-versions-and-more@main

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 #v4
        with:
          dependency-graph: generate-and-submit

      - name: Compile and test
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          ./gradlew ${{ env.buildarg }} ${{ inputs.sbom-build }} --no-daemon
          jarfile=$(ls -1s ${{ steps.get-versions.outputs.docker-dir }}/build/libs/*.jar | sort -n | tail -1 | cut -d' ' -f 2)
          jar -tf $jarfile | grep -q spring-boot-jarmode-tools
          if [ $? = 0 ]; then java -Djarmode=tools -jar $jarfile extract --destination ${{ steps.get-versions.outputs.docker-dir }}/build/libs/app; fi 

      - name: Tag
        run: |
          git tag -a ${{ steps.get-versions.outputs.next-version }} -m 'tagging as v${{ steps.get-versions.outputs.next-version }}'
          git push origin ${{ steps.get-versions.outputs.next-version }}

      - name: Docker build and push
        uses: nais/docker-build-push@ea11cfb8d47d78fab1231145e34699714efad5b7 # v0.16.0
        with:
          team: teameresept
          docker_context: ${{ steps.get-versions.outputs.docker-dir }}
          dockerfile: ${{ steps.get-versions.outputs.docker-dir }}/Dockerfile
          identity_provider: ${{ secrets.identity-provider }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ steps.get-versions.outputs.next-version }}
          build_args: |
            version=${{ steps.get-versions.outputs.next-version }}
            app_name=${{ inputs.application }}
#          byosbom: ${{ inputs.sbom-path }} # use trivy by default

      - name: Checkout badges
        uses: navikt/eresept-actions/badges-checkout@main

      - name: Calculate execution time
        run: |
          END_TIME=$(date +%s)
          echo "exectime=$(( $END_TIME - ${{ env.starttime }} ))" >> $GITHUB_ENV

      - name: Version badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'version'
          right: '${{ steps.get-versions.outputs.next-version }}'
          color: 'blue'
          filename: 'version'
          logo: 'tag'

      - name: Release date badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'release date'
          right: '${{ steps.get-versions.outputs.current-datetime }}'
          color: 'blue'
          filename: 'rel-date'
          logo: 'calendar'

      - name: Time used badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'release execution time'
          right: '${{ env.exectime }}'
          color: 'blue'
          filename: 'rel-exec-time'
          logo: 'stopwatch'

      - name: Commit badges
        uses: navikt/eresept-actions/badges-commit@main

      - name: Summary
        run: |
          echo "### Released **${{ github.event.repository.name }}:${{ steps.get-versions.outputs.next-version }}** in ${{ env.exectime }} seconds" >> $GITHUB_STEP_SUMMARY

      - name: report to slack
        if: always()
        uses: navikt/eresept-actions/slack-notify@main
        with:
          status: "${{ job.status }}"
          username: "release ${{ inputs.application }}:${{ steps.get-versions.outputs.next-version }}"
          icon: ":docker:"
          title-success: "Released _*${{ inputs.application }}:${{ steps.get-versions.outputs.next-version }}*_ in ${{ env.exectime }} seconds"
          title-failure: "Release of _*${{ inputs.application }}*_ failed"
          title-cancelled: "Release of _*${{ inputs.application }}*_ was cancelled"
          message-success: "```${{ steps.get-versions.outputs.changelog }}```"
          webhook: ${{ secrets.webhook }}
