name: Gradle release application, re-usable
on:
  workflow_call:
    inputs:
      java-version:
        description: the java version to use
        required: false
        type: number
        default: 21
      application:
        description: 'The application to release'
        required: true
        type: string
        # no default
      application-version:
        description: 'The version to release'
        required: false
        type: string
        # no default
      skip-tests:
        description: 'if execution of tests should be skipped'
        required: false
        type: boolean
        default: false
      sbom-build:
        description: 'command to use when building sbom'
        required: false
        type: string
        default: 'cyclonedxBom'
      sbom-path:
        description: 'where to find the sbom file'
        required: false
        type: string
        default: 'build/reports/bom.json'
    secrets:
      webhook:
        required: true
      token:
        required: true
      identity-provider:
        required: true

jobs:
  release:
    timeout-minutes: 40
    name: Release ${{ inputs.application }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 0
          repository: navikt/${{ inputs.application }}

      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 #v4.0.0
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'

      - name: Set some variables
        run: |
          echo "starttime=$(date +%s)" >> $GITHUB_ENV
          sudo timedatectl set-timezone "Europe/Oslo"
          echo "buildarg=$(if [ '${{ inputs.skip-tests }}' = 'true' ]; then echo 'assemble'; else echo 'build'; fi)" >> $GITHUB_ENV 

      - id: version-numbers
        uses: navikt/eresept-actions/get-versions-gradle@main
        with:
          application: ${{ inputs.application }}
          application-version: ${{ inputs.application-version }}

      - name: Updates version numbers
        uses: navikt/eresept-actions/update-version-gradle@main
        if: ${{ steps.version-numbers.outputs.current-version != steps.version-numbers.outputs.release-version }}
        with:
          current: ${{ steps.version-numbers.outputs.current-version }}
          next: ${{ steps.version-numbers.outputs.release-version }}
          file: ${{ steps.version-numbers.outputs.version-file }}

      - name: Compile and test
        id: compile
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 #v2.11.1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          gradle-version: wrapper
          arguments: ${{ env.buildarg }} ${{ inputs.sbom-build }} --no-daemon
          dependency-graph: generate-and-submit

      - name: Tag
        run: |
          git tag -a v${{ steps.version-numbers.outputs.release-version }} -m 'tagging as v${{ steps.version-numbers.outputs.release-version }} [ci skip]'

      - name: Bumb version
        uses: navikt/eresept-actions/update-version-gradle@main
        with:
          current: ${{ steps.version-numbers.outputs.release-version }}
          next: ${{ steps.version-numbers.outputs.next-version }}
          file: ${{ steps.version-numbers.outputs.version-file }}

      - name: Commit to git
        run: |
          git push -f origin v${{ steps.version-numbers.outputs.release-version }} main

      - name: Docker build and push
        uses: nais/docker-build-push@1d8fa37371227a83cc5f1f491d528f572341eb09 # v0.11.1
        with:
          team: teameresept
          docker_context: ${{ steps.version-numbers.outputs.docker-dir }}
          dockerfile: ${{ steps.version-numbers.outputs.docker-dir }}/Dockerfile
          identity_provider: ${{ secrets.identity-provider }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ steps.version-numbers.outputs.release-version }}
          build_args: |
            version=${{ steps.version-numbers.outputs.release-version }}
            app_name=${{ inputs.application }}
          byosbom: ${{ inputs.sbom-path }}

      - name: Checkout badges
        uses: navikt/eresept-actions/badges-checkout@main

      - name: Calculate execution time
        run: |
          END_TIME=$(date +%s)
          echo "exectime=$(( $END_TIME - ${{ env.starttime }} ))" >> $GITHUB_ENV

      - name: Version badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'version'
          right: '${{ steps.version-numbers.outputs.release-version }}'
          color: 'blue'
          filename: 'version'
          logo: 'tag'

      - name: Release date badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'release date'
          right: '${{ steps.version-numbers.outputs.release-date }}'
          color: 'blue'
          filename: 'rel-date'
          logo: 'calendar'

      - name: Time used badge
        uses: navikt/eresept-actions/badges-create@main
        with:
          left: 'release execution time'
          right: '${{ env.exectime }}'
          color: 'blue'
          filename: 'rel-exec-time'
          logo: 'stopwatch'

      - name: Commit badges
        uses: navikt/eresept-actions/badges-commit@main

      - name: Summary
        run: |
          echo "### Released **${{ github.event.repository.name }}:${{ steps.version-numbers.outputs.release-version }}** in ${{ env.exectime }} seconds" >> $GITHUB_STEP_SUMMARY

      - name: report to slack
        if: always()
        uses: navikt/eresept-actions/slack-notify@main
        with:
          status: "${{ job.status }}"
          username: "release ${{ steps.version-numbers.outputs.app-version }}"
          icon: ":docker:"
          title-success: "Released _*${{ steps.version-numbers.outputs.app-version }}*_ in ${{ env.exectime }} seconds"
          title-failure: "Release of _*${{ inputs.application }}*_ failed"
          title-cancelled: "Release of _*${{ inputs.application }}*_ was cancelled"
          message-success: "```${{ steps.version-numbers.outputs.changelog }}```"
          webhook: ${{ secrets.webhook }}
