name: Snyk monitor, re-usable

on:
  workflow_call:
    inputs:
      threshold:
        description: 'severity threshold, default high'
        type: string
        required: false
        default: 'high'
    secrets:
      snyk-token:
        required: true
      token:
        description: 'github token'
        required: true

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
      - name: create settings.xml
        uses: whelk-io/maven-settings-xml-action@8a613be18185c8521e1501081adad5041840f2c8 #v20
        with:
          repositories: '[{ "id": "eresept-parent", "name": "github", "url": "https://maven.pkg.github.com/navikt/eresept-parent", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }, { "id": "xerces", "name": "github", "url": "https://maven.pkg.github.com/navikt/xerces-xmlschema-1.1", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "eresept-parent", "username": "${{ github.actor }}", "password": "${{ secrets.token }}" }, { "id": "xerces", "username": "${{ github.actor }}", "password": "${{ secrets.token }}" }]'
          output_file: snyk-settings.xml
      - name: creates a project in your Snyk account to be continuously monitored
        uses: snyk/actions/maven@7fad562681122205233d1242c3bb39598c5393da #master 2022-05-19
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          command: monitor
          args: --org=teameresept --severity-threshold=${{ inputs.threshold }} --all-projects --exclude=report -- --settings snyk-settings.xml -DskipTests -Dmdep.skip=true -Dgitlog.phase=none
