name: Snyk scanning, re-usable

on:
  workflow_call:
    secrets:
      snyk-token:
        required: true

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: creates a project in your Snyk account to be continuously monitored
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          command: monitor
          args: |
            --org=teameresept
            --project-name=${{ github.event.repository.name }}

  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run Snyk to test dependencies for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          command: test
          args: |
            --org=teameresept
            --project-name=${{ github.event.repository.name }}
