name: Snyk monitor, re-usable

on:
  workflow_call:
    inputs:
      threshold:
        description: 'severity threshold, default high'
        type: string
        required: false
        default: 'high'
    secrets:
      snyk-token:
        required: true
      token:
        description: 'github token'
        required: true

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f #v4.1.3
      - name: create settings.xml
        uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d #v22
        with:
          repositories: '[{ "id": "eresept-parent", "name": "github", "url": "https://maven.pkg.github.com/navikt/eresept-parent", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }, { "id": "xerces", "name": "github", "url": "https://maven.pkg.github.com/navikt/xerces-xmlschema-1.1", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "eresept-parent", "username": "${{ github.actor }}", "password": "${{ secrets.token }}" }, { "id": "xerces", "username": "${{ github.actor }}", "password": "${{ secrets.token }}" }]'
          output_file: snyk-settings.xml
      - name: creates a project in your Snyk account to be continuously monitored
        uses: snyk/actions/maven@b98d498629f1c368650224d6d212bf7dfa89e4bf #master 2022-11-29
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          command: monitor
          args: --org=teameresept --severity-threshold=${{ inputs.threshold }} --all-projects --exclude=report -- --settings snyk-settings.xml -DskipTests -Dmdep.skip=true -Dgitlog.phase=none
