name: Snyk scanning, re-usable

on:
  workflow_call:
    inputs:
      exclude:
        description: 'exclude options, eg: dir1,dir2'
        type: string
        required: false
      build:
        description: 'flag to indicate if we need to build project before calling snyk, typically done on multi-module projects'
        type: boolean
        required: false
        default: false
    secrets:
      snyk-token:
        required: true
      token:
        description: 'github token'
        required: true

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "eresept-parent", "name": "github", "url": "https://maven.pkg.github.com/navikt/eresept-parent", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "eresept-parent", "username": "${{ github.actor }}", "password": "${{ secrets.token }}" }]'
          output_file: snyk-settings.xml
      - name: build
        if: ${{ inputs.build }}
        run: mvn install -DskipTests -Dgitlog.phase=none -s snyk-settings.xml
      - name: creates a project in your Snyk account to be continuously monitored
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          command: monitor
          args: --org=teameresept --severity-threshold=high --all-projects --exclude=report,${{ inputs.exclude }} -- --settings snyk-settings.xml
